# Generated by Django 3.1.7 on 2021-03-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210330_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_fiis58.jpg', upload_to='forthegram_profile_pics'),
        ),
    ]
